#!/bin/bash

while true
DATE_WITH_TIME=`date "+%Y%m%d-%H%M%S"`
do
	if [ "$1" == "history" ]; then
		DATE_WITH_TIME="$DATE_WITH_TIME-charging-location.kml"
		wget -O - q http://esb.ie/electric-cars/kml/charging-locations.kml > ./historic_data/$DATE_WITH_TIME
		sleep 1800
	else
		wget -O - q http://esb.ie/electric-cars/kml/charging-locations.kml > charging-location.kml
		sleep 1800
	fi
done
